version: '3.7'

services:
  db:
    build:
      context: ./Database
      dockerfile: Dockerfile.PostgreSQL
    ports:
      - ${PG_PORT}:${PG_PORT}
    networks:
      - mud-network
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
      - IURI_PASSWORD=${IURI_PASSWORD}
      - MAURICIO_PASSWORD=${MAURICIO_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "unmud"]
      interval: 10s
      timeout: 5s
      retries: 5

  unmud:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/UnMUD
    volumes:
      - type: bind
        source: .
        target: /usr/src/UnMUD
    networks:
      - mud-network
    expose:
      - ${MUD_PORT}
    ports:
      - ${MUD_PORT}:${MUD_PORT}
    environment:
      - PGHOST=${PG_HOST}
      - PGPORT=${PG_PORT}
      - PGDATABASE=${PG_DATABASE}
      - PGUSER=${PG_USER}
      - PGPASSWORD=${PG_PASSWORD}
      - MUD_PORT=${MUD_PORT}
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - db
    networks:
      - mud-network  

volumes:
  db_data:

networks:
  mud-network:
    driver: bridge